app:
  name: sample
  description: spring cloud boilerplate api sample

server:
  port: 8080
  address: 0.0.0.0
  session:
    timeout: 360000

####################### eureka configuration #######################
eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOST:localhost}
    non-secure-port: ${EUREKA_INSTANCE_PORT:8080}
    prefer-ip-address: false
#    statusPageUrlPath: ${server.servletPath}/info
#    healthCheckUrlPath: ${server.servletPath}/health
#    statusPageUrl: https://${eureka.instance.hostname}/info
#    healthCheckUrl: https://${eureka.instance.hostname}/health
#    homePageUrl: https://${eureka.instance.hostname}/
    instance-id: ${spring.application.name}:${eureka.instance.hostname}:${eureka.instance.non-secure-port}:${random.value}
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:'http://localhost:8761/eureka/'}
