server:
  port: 10000

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
#    instance-id: ${app.name}:${spring.application.name}:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
       defaultZone: http://${eureka.instance.hostname}:8761/eureka/

zuul:
  routes:
    resource:
      path: /iamsvc/**
      url: ${ZUUL_ROUTES_IAMSVC_URL}
#
#sidecar:
#  port: 80

security:
  sessions: NEVER