version: '2'
services:
  sample-node1:
    container_name: sample-node1
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - redis-server
    links:
      - redis-server:${REDIS_HOST}
    ports:
      - "8081:8080"
    environment:
      EUREKA_INSTANCE_HOST: ${DEVOPS_HOST}
      EUREKA_INSTANCE_PORT: "8081"
      EUREKA_SERVICE_URL: ${EUREKA_SERVICE_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      JAVA_OPTS: -Xmx1024m -Xms256m
  sample-node2:
    container_name: sample-node2
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - redis-server
    links:
      - redis-server:${REDIS_HOST}
    ports:
      - "8082:8080"
    environment:
      EUREKA_INSTANCE_HOST: ${DEVOPS_HOST}
      EUREKA_INSTANCE_PORT: "8082"
      EUREKA_SERVICE_URL: ${EUREKA_SERVICE_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      JAVA_OPTS: -Xmx1024m -Xms256m
  redis-server:
    container_name: redis-server
    image: redis:alpine
